[package]
name = "aoc-2020"
version = "0.1.0"
authors = ["Thomas BARUSSEAU <thomas.barusseau@thetribe.io>"]
edition = "2018"

[lib]
# bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
rayon = "1.5.0"
